#!/usr/bin/env bash

PROJECT_DIR="$PREFIX/share/storm-framework"
cd "$PROJECT_DIR" || { echo "[x] ERROR: Failed to access project directory."; exit 1; }

if [ "$1" = "--update" ] && [ $# -eq 1 ]; then
    exec ./smfupdate --data Termux

elif [ "$1" = "--cp" ] && [ "$2" = "--crt" ] && [ $# -eq 2 ]; then

    if [ ! -f "./data/smf_ca.crt" ]; then
        echo "[x] ERROR: smf_ca.crt not found."
        exit 1
    fi

    cp ./data/smf_ca.crt "$HOME/smf_ca.crt"

    echo "[+] Certificate copied to: $HOME/smf_ca.crt"

elif [ "$1" = "-v" ] || [ "$1" = "--version" ] && [ $# -eq 1 ]; then

    version=$(jq -r '.version' data/data.json)
    echo "[*] Version: $version"

elif [ "$1" = "-v" ] && [ "$2" = "-L" ] && [ $# -eq 2 ]; then

    latest_version=$(curl -fsSL "https://raw.githubusercontent.com/StormWorld0/storm-framework/main/data/data.json" | jq -r '.version')
    current_version=$(jq -r '.version' data/data.json)

    if [ "$(printf '%s\n' "$current_version" "$latest_version" | sort -V | tail -n1)" != "$current_version" ]; then
        echo "[*] Update available: $current_version -> $latest_version"
    else
        echo "[*] Already up to date: $current_version"

elif [ "$1" = "-h" ] || [ "$1" = "--help" ] && [ $# -eq 1 ]; then

    echo "Arguments:"
    echo "    [-h][--help]     : Displays existing commands"
    echo "    [-v][--version]  : Displays the current version"
    echo "    [-v -L]          : Shows whether the latest update is available"
    echo "    [-cp -crt]       : Copying CA to HOME Directory"
    echo "    [--update]       : Update to the latest version"

elif [ $# -eq 0 ]; then

    if [ ! -f "./smfstart" ]; then
        exec ./smfupdate --data Termux
    else
        exec ./smfstart
    fi

else
    echo "[*] Invalid arguments: $@"
    exit 1
fi
