[project]
name = "Storm-Framework"
version = "3.10"
authors = [
    {name = "エルジー", email = "elzyproot@protonmail.com"}
]
description = "Just a Storm Framework. All-in-one Pentest tool."
readme = "README.md"
requires-python = ">=3.13"
license = {text = "GPL-3.0"}
classifiers = [
    "License :: OSI Approved :: GPL License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Golang",
    "Programming Language :: Rust",
    "Programming Language :: Bash"
]
keywords=["storm", "python", "tool-suite", "offensive-security", "storm-framework"]

[tool.black]
line-length = 90
target-version = ['py313']
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | .*/vendor/.*
    | example/
)/
'''

[tool.pyrefly]
search_path = ["."]

[tool.pyright]
executionEnvironments = [
  { root = "." }
]

[tool.mypy]
mypy_path = "."
