#!/usr/bin/env bash
set -e

# --- CONFIGURATION ---
TOOL_NAME="storm"
REPO_NAME="storm-framework"
WRAPPER_URL="https://raw.githubusercontent.com/StormWorld0/$REPO_NAME/main/docker/bin/$TOOL_NAME"
DOCKER_IMAGE="zxelzy/$REPO_NAME"

# Color
GREEN='\033[92m'
RED='\033[91m'
YELLOW='\033[93m'
NC='\033[0m'

# --- OS DETECTION ---
OS="$(uname -s)"
case "${OS}" in
    Linux*|Darwin*)
        echo -e "${GREEN}[+] OS Detected: ${OS}${NC}"
        ;;
    *)
        echo -e "${RED}[*] OS not recognized: ${OS}${NC}"
        exit 1
        ;;
esac

# --- PULL DOCKER IMAGE ---
docker pull "$DOCKER_IMAGE"

# --- DOWNLOAD & INSTALL WRAPPER ---
TARGET_PATH="/usr/local/bin/$TOOL_NAME"

# Validation (sudo)
if [ "$EUID" -ne 0 ]; then
    sudo curl -sL "$WRAPPER_URL" -o "$TARGET_PATH"
    sudo chmod +x "$TARGET_PATH"
else
    curl -sL "$WRAPPER_URL" -o "$TARGET_PATH"
    chmod +x "$TARGET_PATH"
fi

echo -e "${GREEN}[✓] INSTALLATION COMPLETE${NC}"
