#!/usr/bin/env bash
set -e

# --- CONFIGURATION ---
TOOL_NAME="storm"
REPO_NAME="storm-framework"
WRAPPER_URL="https://raw.githubusercontent.com/StormWorld0/$REPO_NAME/main/docker/bin/$TOOL_NAME"
DOCKER_IMAGE="stormworld0/$REPO_NAME:latest"

# Color
GREEN='\033[92m'
RED='\033[91m'
YELLOW='\033[93m'
NC='\033[0m'

# --- OS DETECTION ---
OS="$(uname -s)"

case "${OS}" in
    Linux*)
        echo -e "${GREEN}[+] Linux Detected: ${OS}${NC}"
        ;;
    Darwin*)
        echo -e "${GREEN}[+] MacOS Detected: ${OS}${NC}"
        ;;
    *)
        echo -e "${RED}[*] OS not recognized: ${OS}${NC}"
        exit 1
        ;;
esac

# --- INSTALL LIBRARY ---
apt-get install -y curl sudo bash jq docker.io

# --- PULL DOCKER IMAGE ---
docker pull "$DOCKER_IMAGE"

# --- DOWNLOAD & INSTALL WRAPPER ---
XDG_BIN_HOME="$HOME/.local/bin"
TARGET_PATH="$XDG_BIN_HOME/$TOOL_NAME"

# Create a folder if it doesn't exist
mkdir -p "$XDG_BIN_HOME"

# Download wrapper
curl -sL "$WRAPPER_URL" -o "$TARGET_PATH"
chmod +x "$TARGET_PATH"

# Installation complete
echo -e "${GREEN}[✓] INSTALLATION COMPLETE${NC}"
