#!/usr/bin/env python3

# --- https://github.com/StormWorld0/storm-framework ---
# SMF License
# copyright (c) 2026
# Complete information about the License is in the root directory.
# Author: zxelzy

import readline  # noqa: F401
import sys
import smf

try:
    from lib.ui.interface import systemb
    systemb()
except ImportError as e:
    smf.printf(f"Error import smfstart =>", e, file=sys.stderr)
    sys.exit(100)
