#!/usr/bin/env python3

# --- https://github.com/StormWorld0/storm-framework ---
# SMF License
# copyright (c) 2026
# Complete information about the License is in the root directory.
# Author: zxelzy

try:
    import sys
    from lib.ui.helpers import update
    from scripts.wrapper.gen_wrapper import generate
except ImportError as e:
    print("[!] Error import smfupdate => {e}")


wrapper = None
try:
    update()

    if "--data" in sys.argv:
        index = sys.argv.index("--data")

        if index + 1 < len(sys.argv):
            wrapper = sys.argv[index + 1]

    generate(wrapper)
except Exception as e:
    print(f"Error smfupdate => {e}")
    sys.exit(1)
