[package]
name = "storm-framework"
version = "1.0.0"
edition = "2024"

[lib]
name = "smf"
crate-type = ["cdylib"]

[dependencies]
# abi3-py39 ensure to match minimum Python version 3.9
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py39"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
rand = "0.10.2"

[profile.release]
lto = true            # Link-Time Optimization (optimization across .rs files)
codegen-units = 1     # Reduce compilation parallelization for maximum optimization
panic = "abort"       # Reduce binary size & speed up execution on crash
strip = true          # Remove debug symbols to make .so files lighter
